apiVersion: apps/v1
kind: Deployment
metadata:
  name: deno-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deno
  template:
    metadata:
      labels:
        app: deno
    spec:
      containers:
      - name: deno
        image: 211223789150.dkr.ecr.us-east-1.amazonaws.com/my-docker-repo
        ports:
        - containerPort: 8080

 
 # load balancer
 ---
 apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: deno-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: deno.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: deno-service
            port: 80
              name: http

